### ISSUE TITLE
BYU Logo Link

### ISSUE THREAD

**Issue by bmorgan296** [byuweb/byu2017_d7#33]
The user doesn't have a way to change the BYU logo link to point to their website in the theme settings, so it always points to byu.edu rather than where the user wants it to point.

**Comment by katrialesser** [comment]
We need to add a) the site's homepage url to the template, or b) add a link field, which defaults to the front page. It looks like with components we are allowing users to choose this url so we'll go with option b.

Need to add this to our byu-header tag:  home-url="http://web.byu.edu
as documented: http://2017-components-demo.cdn.byu.edu/byu-header.html
