### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by dallinlee1** [byuweb/byu2017_d7#45]
I followed the install and download instructions for the new web theme for cellphone-mesh.byu.edu and am getting a weird error that has to do with the theme. I have to refresh the page after loading it the first time to see the error. 

![homepage](https://user-images.githubusercontent.com/21693337/30345095-1e07cb7c-97c1-11e7-8384-c6fa3685c664.png)
![blockspage](https://user-images.githubusercontent.com/21693337/30345101-20fb0088-97c1-11e7-9231-1a408938c1b7.png)

**Comment by katrialesser** [comment]
This is definitely related to the footer. Since it uses components I have to format the block content and send it to the component without a lot of the wrapping divs. Can you try adding a block in each of the 4 footer columns and we'll see if that makes it go away? Just so I know.

Also, is your drupal 7 core version up to date? Or did you update recently? What version are you on? It seems like this is a conflict with something the block module is doing. Maybe there's a difference since I wrote this code.

**Comment by katrialesser** [comment]
@dallinlee1 ^ can you provide some more info?

**Comment by dallinlee1** [comment]
We are using Drupal 7.56. This is from a fresh install and there are no errors showing up in the status report page. I added items in the footer and got more errors than before.

![homepage2](https://user-images.githubusercontent.com/21693337/30348991-85b316a2-97ce-11e7-9edb-af76666e82dc.png)

**Comment by katrialesser** [comment]
Alright, trying to reproduce: 
I have 7.56 installed, fresh install, just enabled the byu_d8 theme. I also have zurb_foundation 4 like the instructions say.

I have placed a drupal-generated block, like one pictured in one footer column and one custom block. I am wondering what you have in column 1 @dallinlee1 - it looks like a completely empty block, but Drupal 7 requires that *something* be entered in the body of a custom block. So I need to know what you have there and how you got it there.

Here is what I have so far trying to reproduce:
![image](https://user-images.githubusercontent.com/12898896/30402121-eaa8f880-9899-11e7-885c-d435d1f5001e.png)

Please explain what block is in column 1 and any other steps you may have taken. Thanks!

**Comment by katrialesser** [comment]
*Corrected: I meant I enabled the d7 theme to reproduce what he had done.

We solved this in slack conversation: The theme by default places the search in the search region, the main navigation block in the main navigation region. Then you can create and add a single-link block into the header actions regions, per the instructions. He had placed the search and navigation blocks into the header actions regions instead, and making that change broke things. If the blocks stay where they are set by default, this issue won't come up for people.
