### ISSUE TITLE
Add font options for google fonts in header font options

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu2017_d7#46]
libre baskerville and source sans

Make it not break if they select one without the fonts enabled above, or make them only in the dropdown if they are enabled above etc.

**Comment by rburkey87** [comment]
Not showing the issue (no source sans available at all), but did notice that changing the paragraph font also affects the components that have paragraph tags, like the action links and footer links. I suggest we adjust the scss selector to `#page-container p`

**Comment by katrialesser** [comment]
Go ahead and add in settings for checkboxes for the other google fonts enabling, see d8 theme./

https://github.com/byuweb/byu_d8/blob/master/theme-settings.php

Add to include the css
https://github.com/byuweb/byu_d8/blob/master/byu_d8.theme

```
   // we need an intro class to initialize the array so the next pushes/additions go through correctly - don't remove!
    $variables['attributes']['class'][] = 'body';

    $font_one = "h1-" . theme_get_setting('font_one');
    $font_two = "h2-" . theme_get_setting('font_two');
    $font_three = "h3-" . theme_get_setting('font_three');
    $font_four = "h4-" . theme_get_setting('font_four');
    $font_five = "h5-" . theme_get_setting('font_five');
    $font_one_color = theme_get_setting('font_one_color');
    $font_two_color = theme_get_setting('font_two_color');
    $font_three_color = theme_get_setting('font_three_color');
    $font_four_color = theme_get_setting('font_four_color');
    $font_five_color = theme_get_setting('font_five_color');
    $p_font = "p-" . theme_get_setting('p_font');

    array_push($variables['attributes']['class'],$font_one, $font_two, $font_three, $font_four, $font_five, $font_one_color, $font_two_color, $font_three_color, $font_four_color, $font_five_color, $p_font);
```
