### ISSUE TITLE
Footer columns aligning incorrectly outside Chrome

### ISSUE THREAD

**Issue by rburkey87** [byuweb/byu2017_d7#50]
# Description
Footer column content is aligning right in Firefox, Edge, and IE11. Unsure about Safari.

**If the issue is with styling, please include screenshots!**
![image](https://user-images.githubusercontent.com/25965299/30754909-d3fd0dd0-9f81-11e7-83e5-daba1b386856.png)

# Websites Affected
https://calendar-test.byu.edu/

**Comment by katrialesser** [comment]
Shawn Ward experienced this in firefox, has this fix and still sees the issue.

**Comment by katrialesser** [comment]
Closing again: It was his prepro and sassy modules not precompiling the scss files.
